# Generated by Django 6.0.1 on 2026-01-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chess_com_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pgn', models.TextField()),
                ('white_player', models.CharField(max_length=255)),
                ('black_player', models.CharField(max_length=255)),
                ('white_elo', models.IntegerField(blank=True, null=True)),
                ('black_elo', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(max_length=10)),
                ('time_control', models.CharField(blank=True, max_length=50, null=True)),
                ('game_type', models.CharField(blank=True, max_length=50, null=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blunder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('fen_before', models.CharField(max_length=100)),
                ('fen_after', models.CharField(max_length=100)),
                ('actual_move', models.CharField(max_length=10)),
                ('best_move', models.CharField(max_length=10)),
                ('player_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('eval_before', models.FloatField()),
                ('eval_after', models.FloatField()),
                ('eval_delta', models.FloatField()),
                ('blunder_type', models.CharField(choices=[('blunder', 'Blunder'), ('mistake', 'Mistake'), ('inaccuracy', 'Inaccuracy')], default='blunder', max_length=20)),
                ('severity', models.FloatField(default=0.0)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('analysis_params', models.JSONField(blank=True, default=dict)),
                ('continuations', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blunders', to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_move', models.CharField(max_length=10)),
                ('outcome', models.CharField(choices=[('best_move', 'Best Move'), ('was_blunder', 'Was Blunder'), ('neither', 'Neither')], max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('blunder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.blunder')),
            ],
        ),
    ]
